version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-west-1 --no-include-email)
      - REPOSITORY_URI=__ACCOUNT_NUMBER__.dkr.ecr.us-west-1.amazonaws.com/nodejs-fargate
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodejs-fargate:latest .
      - docker tag nodejs-fargate:latest public.ecr.aws/r9c1h1x1/nodejs-fargate:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/r9c1h1x1/nodejs-fargate:latest
      - docker push public.ecr.aws/r9c1h1x1/nodejs-fargate
      - echo Writing image definitions file...
      - printf '[{"name”:"myvpc-task","imageUri":"%s"}]' public.ecr.aws/r9c1h1x1/nodejs-fargate:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
